# CMake generated Testfile for 
# Source directory: /home/cyy/computation/test
# Build directory: /home/cyy/computation/build26/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[canonical_lr_grammar_test]=] "/home/cyy/computation/build26/test/canonical_lr_grammar_test")
set_tests_properties([=[canonical_lr_grammar_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[cfg_test]=] "/home/cyy/computation/build26/test/cfg_test")
set_tests_properties([=[cfg_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[cnf_test]=] "/home/cyy/computation/build26/test/cnf_test")
set_tests_properties([=[cnf_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[dcfg_test]=] "/home/cyy/computation/build26/test/dcfg_test")
set_tests_properties([=[dcfg_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[dk_1_test]=] "/home/cyy/computation/build26/test/dk_1_test")
set_tests_properties([=[dk_1_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[dk_test]=] "/home/cyy/computation/build26/test/dk_test")
set_tests_properties([=[dk_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[dpda_test]=] "/home/cyy/computation/build26/test/dpda_test")
set_tests_properties([=[dpda_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[endmarked_dpda_test]=] "/home/cyy/computation/build26/test/endmarked_dpda_test")
set_tests_properties([=[endmarked_dpda_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[lalr_grammar_test]=] "/home/cyy/computation/build26/test/lalr_grammar_test")
set_tests_properties([=[lalr_grammar_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[ll_grammar_test]=] "/home/cyy/computation/build26/test/ll_grammar_test")
set_tests_properties([=[ll_grammar_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[pda_test]=] "/home/cyy/computation/build26/test/pda_test")
set_tests_properties([=[pda_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[slr_grammar_test]=] "/home/cyy/computation/build26/test/slr_grammar_test")
set_tests_properties([=[slr_grammar_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[dfa_test]=] "/home/cyy/computation/build26/test/dfa_test")
set_tests_properties([=[dfa_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[gnfa_test]=] "/home/cyy/computation/build26/test/gnfa_test")
set_tests_properties([=[gnfa_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[nfa_test]=] "/home/cyy/computation/build26/test/nfa_test")
set_tests_properties([=[nfa_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[regex_test]=] "/home/cyy/computation/build26/test/regex_test")
set_tests_properties([=[regex_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
add_test([=[turing_machine_test]=] "/home/cyy/computation/build26/test/turing_machine_test")
set_tests_properties([=[turing_machine_test]=] PROPERTIES  WORKING_DIRECTORY "/home/cyy/computation/build26" _BACKTRACE_TRIPLES "/home/cyy/computation/cmake/test.cmake;297;add_test;/home/cyy/computation/cmake/test.cmake;306;__test_impl;/home/cyy/computation/test/CMakeLists.txt;15;add_test_with_runtime_analysis;/home/cyy/computation/test/CMakeLists.txt;0;")
